# Powerlevel10k 精致配置
# 现代、简洁、彩色的 prompt 样式

# 启用即时提示模式
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# 基本设置
POWERLEVEL9K_MODE='nerdfont-v3'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{cyan}❯%f '

# 左侧提示符元素
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon           # NixOS 图标
  dir               # 当前目录
  vcs               # Git 状态
)

# 右侧提示符元素
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status                      # 上一条命令状态
  command_execution_time      # 命令执行时间
  background_jobs             # 后台任务数量
  virtualenv                  # Python 虚拟环境
  context                     # 用户@主机
  time                        # 时间
)

# OS 图标样式 - 无背景
POWERLEVEL9K_OS_ICON_FOREGROUND=cyan
POWERLEVEL9K_OS_ICON_BACKGROUND=none

# 目录样式 - 无背景，fish-style 缩短
POWERLEVEL9K_DIR_FOREGROUND=blue
POWERLEVEL9K_DIR_BACKGROUND=none
POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=cyan
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_DIR_SHOW_WRITABLE=true
POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
# 显示前面目录的首字母，完整显示最后 2 层
POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=cyan
POWERLEVEL9K_DIR_ANCHOR_BOLD=true

# Git/VCS 样式 - 无背景，根据状态变色
POWERLEVEL9K_VCS_CLEAN_FOREGROUND=green
POWERLEVEL9K_VCS_CLEAN_BACKGROUND=none
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=yellow
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=none
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=red
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=none

# 状态样式 - 无背景
POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_STATUS_ERROR_FOREGROUND=red
POWERLEVEL9K_STATUS_ERROR_BACKGROUND=none

# 命令执行时间 - 无背景
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=yellow
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=none
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3

# 后台任务 - 无背景
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=magenta
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=none

# 时间 - 无背景
POWERLEVEL9K_TIME_FOREGROUND=white
POWERLEVEL9K_TIME_BACKGROUND=none
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'

# 上下文 (用户@主机) - 无背景
POWERLEVEL9K_CONTEXT_FOREGROUND=cyan
POWERLEVEL9K_CONTEXT_BACKGROUND=none
POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND=green

# 虚拟环境 - 无背景
POWERLEVEL9K_VIRTUALENV_FOREGROUND=blue
POWERLEVEL9K_VIRTUALENV_BACKGROUND=none

# 分隔符 - 紧凑间距
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''

# 元素间距
POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=' '

# 图标和内容间距
POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=''
POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

# 左右 padding - 减少间距
POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_START_SEPARATOR=''

# 瞬时提示
POWERLEVEL9K_INSTANT_PROMPT=verbose
POWERLEVEL9K_TRANSIENT_PROMPT=same-dir
