# Powerlevel10k 精致配置
# 现代、简洁、彩色的 prompt 样式

# 启用即时提示模式
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# 基本设置
POWERLEVEL9K_MODE='nerdfont-v3'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{cyan}❯%f '

# 左侧提示符元素
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon           # NixOS 图标
  dir               # 当前目录
  vcs               # Git 状态
)

# 右侧提示符元素
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status                      # 上一条命令状态
  command_execution_time      # 命令执行时间
  background_jobs             # 后台任务数量
  virtualenv                  # Python 虚拟环境
  context                     # 用户@主机
  time                        # 时间
)

# OS 图标样式 - 青色背景
POWERLEVEL9K_OS_ICON_FOREGROUND=0
POWERLEVEL9K_OS_ICON_BACKGROUND=39

# 目录样式 - 蓝色背景
POWERLEVEL9K_DIR_FOREGROUND=0
POWERLEVEL9K_DIR_BACKGROUND=33
POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=0
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_unique"
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_DIR_SHOW_WRITABLE=true

# Git/VCS 样式 - 根据状态变色
POWERLEVEL9K_VCS_CLEAN_FOREGROUND=0
POWERLEVEL9K_VCS_CLEAN_BACKGROUND=2
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=0
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=3
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=0
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=1

# 状态样式
POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_STATUS_ERROR_FOREGROUND=0
POWERLEVEL9K_STATUS_ERROR_BACKGROUND=1

# 命令执行时间
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=0
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=6
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3

# 后台任务
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=0
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=5

# 时间
POWERLEVEL9K_TIME_FOREGROUND=0
POWERLEVEL9K_TIME_BACKGROUND=7
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'

# 上下文 (用户@主机)
POWERLEVEL9K_CONTEXT_FOREGROUND=0
POWERLEVEL9K_CONTEXT_BACKGROUND=3
POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND=0

# 虚拟环境
POWERLEVEL9K_VIRTUALENV_FOREGROUND=0
POWERLEVEL9K_VIRTUALENV_BACKGROUND=4

# 分隔符
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '

# 图标
POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=''
POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

# 瞬时提示
POWERLEVEL9K_INSTANT_PROMPT=verbose
POWERLEVEL9K_TRANSIENT_PROMPT=same-dir
