[ClassicUI]
# 垂直候选列表
Vertical Candidate List=False
# 按屏幕 DPI 使用
PerScreenDPI=True
# 在 X 中使用鼠标滚轮翻页
WheelForPaging=True
# 字体
Font="MesloLGL Nerd Font 13"
# 菜单字体
MenuFont="MesloLGL Nerd Font 12"
# 托盘字体
TrayFont="MesloLGL Nerd Font 12"
# 候选词字体
CandidateFont="MesloLGL Nerd Font 13"
# 预编辑字体
PreeditFont="MesloLGL Nerd Font 13"
# 托盘标签轮廓颜色
TrayOutlineColor=#000000
# 托盘标签文本颜色
TrayTextColor=#ffffff
# 优先使用输入法语言显示文本
PreferTextIcon=False
# 在图标中显示布局名称
ShowLayoutNameInIcon=True
# 使用输入法的语言来显示文本
UseInputMethodLanguageToDisplayText=True
# 主题
Theme=macOS-dark
