#!/usr/bin/env bash

# 获取电池状态
BATTERY_INFO=$(acpi -b)
PERCENTAGE=$(echo $BATTERY_INFO | grep -o '[0-9]*%' | tr -d '%')
STATUS=$(echo $BATTERY_INFO | grep -o 'Discharging\|Charging\|Full')

# 选择适当的图标
if [[ "$STATUS" == "Charging" ]]; then
  ICON="<span font='Font Awesome 6 Free'></span>"
elif [[ "$STATUS" == "Full" ]]; then
  ICON="<span font='Font Awesome 6 Free'></span>"
else
  if [[ $PERCENTAGE -le 10 ]]; then
    ICON="<span font='Font Awesome 6 Free'></span>"
  elif [[ $PERCENTAGE -le 25 ]]; then
    ICON="<span font='Font Awesome 6 Free'></span>"
  elif [[ $PERCENTAGE -le 50 ]]; then
    ICON="<span font='Font Awesome 6 Free'></span>"
  elif [[ $PERCENTAGE -le 75 ]]; then
    ICON="<span font='Font Awesome 6 Free'></span>"
  else
    ICON="<span font='Font Awesome 6 Free'></span>"
  fi
fi

echo "$PERCENTAGE% $ICON"
echo "$PERCENTAGE%"

# 颜色提示
if [[ $STATUS != "Charging" && $PERCENTAGE -le 15 ]]; then
  echo "#BF616A" # 红色
elif [[ $STATUS != "Charging" && $PERCENTAGE -le 40 ]]; then
  echo "#EBCB8B" # 黄色
else
  echo "#A3BE8C" # 绿色
fi
