#!/usr/bin/env bash
USAGE=$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {printf "%.0f%%", usage}')
echo "$USAGE"
echo "$USAGE"

# 颜色提示
if [[ ${USAGE%\%} -gt 80 ]]; then
  echo "#BF616A" # 红色
elif [[ ${USAGE%\%} -gt 50 ]]; then
  echo "#EBCB8B" # 黄色
else
  echo "#A3BE8C" # 绿色
fi
