#!/usr/bin/env bash

# 获取音量
VOLUME=$(amixer get Master | grep -o "[0-9]*%" | head -1 | tr -d '%')
MUTED=$(amixer get Master | grep -o "off" | head -1)

# 选择适当的图标
if [[ -n $MUTED ]]; then
  ICON="<span font='Font Awesome 6 Free'></span>"
  echo "$ICON"
  echo "$ICON"
  echo "#BF616A" # 红色
else
  if [[ $VOLUME -eq 0 ]]; then
    ICON="<span font='Font Awesome 6 Free'></span>"
  elif [[ $VOLUME -lt 50 ]]; then
    ICON="<span font='Font Awesome 6 Free'></span>"
  else
    ICON="<span font='Font Awesome 6 Free'></span>"
  fi
  echo "$VOLUME% $ICON"
  echo "$VOLUME%"
  # 无颜色提示
fi
