{config, pkgs, ... }:

{
 imports = [
 ./swww
 ];
  wayland.windowManager.hyprland = {
    enable = true;
    package = pkgs.hyprland;
    xwayland.enable = true;
    extraConfig = ''
    # #######################################################################################
# 自动生成的 HYPRLAND 配置文件（已添加中文注释）                                         #
# 请按照官方 Wiki 指南进行编辑：https://wiki.hypr.land/Configuring/                  #
# #######################################################################################

# 如果保留“autogenerated = 1”则会显示警告，移除可关闭警告提示
#autogenerated = 1

################        显示器 设置        ################
# monitor 格式：<输出设备>,<分辨率>,<刷新率>,<旋转>
monitor = , preferred, auto, 1.25

xwayland {
    force_zero_scaling = true
}

############        常用程序 定义      ############
# 定义常用程序别名，方便后面使用
$terminal     = alacritty         # 默认终端模拟器
$fileManager  = dolphin           # 文件管理器
$menu         = wofi --show drun  # 应用启动器

############        启动时自动运行程序      ############
# exec-once 只执行一次，适合后台守护进程或单例程序
# 其他示例：
# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = firefox
exec-once = waybar

############    环境变量 设置    ############
# 设置光标大小
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

############    权限 配置    ############
# 修改后需重启 Hyprland 生效
#permission = /usr/(bin|local/bin)/grim, screencopy, allow
#permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
#permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

############    外观 与 操作 感受    ############
general {
    gaps_in         = 1        # 窗口内侧间隙
    gaps_out        = 10       # 窗口外侧间隙
    border_size     = 2        # 边框宽度
    col.active_border   = rgba(33ccffee) rgba(00ff99ee) 45deg   # 活动窗口边框渐变色
    col.inactive_border = rgba(595959aa)                     # 非活动窗口边框颜色
    resize_on_border   = false   # 是否可通过拖边框调整大小
    allow_tearing      = false   # 禁用撕裂补偿
    layout             = dwindle # 默认布局：dwindle 链式布局
}

decoration {
    rounding       = 10     # 窗口圆角半径
    rounding_power = 2      # 圆角曲线强度
    active_opacity   = 1.0  # 活动窗口不透明度
    inactive_opacity = 1.0  # 非活动窗口不透明度

    shadow {
        enabled      = true  # 启用阴影
        range        = 4     # 阴影范围
        render_power = 3     # 阴影渲染强度
        color        = rgba(1a1a1aee)  # 阴影颜色
    }

    blur {
        enabled   = true      # 启用模糊效果
        size      = 3         # 模糊半径
        passes    = 1         # 迭代次数
        vibrancy  = 0.1696    # 透明度对比增强
    }
}

############    动画 设置    ############
animations {
    enabled = yes, please :)  # 鲜明表情启用动画
    # 常用 Bézier 曲线配置
    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1

    # 各类动画时长与缓动
    animation = global,      1,10,   default
    animation = border,      1,5.39, easeOutQuint
    animation = windows,     1,4.79, easeOutQuint
    animation = windowsIn,   1,4.1,  easeOutQuint, popin 87%
    animation = windowsOut,  1,1.49, linear, popin 87%
    animation = fadeIn,      1,1.73, almostLinear
    animation = fadeOut,     1,1.46, almostLinear
    animation = fade,        1,3.03, quick
    animation = layers,      1,3.81, easeOutQuint
    animation = layersIn,    1,4,    easeOutQuint, fade
    animation = layersOut,   1,1.5,  linear, fade
    animation = fadeLayersIn,  1,1.79, almostLinear
    animation = fadeLayersOut, 1,1.39, almostLinear
    animation = workspaces,    1,1.94, almostLinear, slide
    animation = workspacesIn,  1,1.21, almostLinear, slide
    animation = workspacesOut, 1,1.94, almostLinear, slide
}

dwindle {
    pseudotile      = true  # 启用伪平铺模式（绑定 Mod+P 切换）
    preserve_split  = true  # 保持拆分布局状态
}

############    主布局 设置    ############
master {
    new_status = master  # 新窗口默认状态设置
}

############    其他 杂项 设置    ############
misc {
    force_default_wallpaper = -1  # 是否强制使用默认壁纸（-1 随机切换）
    disable_hyprland_logo   = false # 是否禁用 Hyprland 默认背景图
}

############    输入 设备    ############
input {
    kb_layout   = us       # 键盘布局
    kb_variant  =          # 布局变体
    follow_mouse = 1       # 自动将焦点跟随鼠标
    sensitivity  = 0       # 鼠标灵敏度调整
    touchpad {
        natural_scroll = false  # 触控板自然滚动
    }
}

gestures {
    workspace_swipe = true  # 多指手势切换工作区
}

device {
    name        = epic-mouse-v1  # 设备名称
    sensitivity = -0.5           # 单设备灵敏度覆盖
}

############    快捷键 绑定    ############
$mainMod = SUPER  # 主修饰键（Windows/Command 键）
# 基本操作
bind = CTRL, 1, exec, ~/.config/hypr/shot-menu.sh;
bind = $mainMod, RETURN, fullscreen, 0

bind  = $mainMod, D, exec, pkill -x rofi || /home/jdk/.local/bin/toggle-rofi.sh;  # 打开/关闭 rofi
bind  = $mainMod, Q, exec, $terminal
bind  = $mainMod, C, killactive,
bind  = $mainMod, M, exit,              # 退出 Hyprland
bind  = $mainMod, E, exec, $fileManager # 打开文件管理器
bind  = $mainMod, V, togglefloating,    # 切换浮动模式
bind  = $mainMod, R, exec, $menu        # 打开应用菜单
bind  = $mainMod, P, pseudo,             # 切换伪平铺模式
bind  = $mainMod, J, togglesplit,        # 切换拆分布局

# 方向导航
bind = $mainMod, left,  movefocus, l  # 左移焦点
bind = $mainMod, right, movefocus, r  # 右移焦点
bind = $mainMod, up,    movefocus, u  # 上移焦点
bind = $mainMod, down,  movefocus, d  # 下移焦点

# 切换工作区（1-10）
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# 移动窗口到指定工作区
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# 特殊工作区（scratchpad）
bind = $mainMod, S, togglespecialworkspace, magic      # 切换隐藏面板
bind = $mainMod SHIFT, S, movetoworkspace, special:magic  # 发送到隐藏面板

# 鼠标滚轮切换工作区
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up,   workspace, e-1

# 鼠标拖动移动/调整窗口
bindm = $mainMod, mouse:272, movewindow  # 拖动移动
bindm = $mainMod, mouse:273, resizewindow # 拖动调整大小

# 多媒体与亮度键
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute,       exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute,    exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

bindl = ,XF86AudioNext,      exec, playerctl next          # 下一首
bindl = ,XF86AudioPause,     exec, playerctl play-pause   # 播放/暂停
bindl = ,XF86AudioPlay,      exec, playerctl play-pause   # 播放/暂停
bindl = ,XF86AudioPrev,      exec, playerctl previous     # 上一首

############    窗口 与 工作区 规则    ############
# 示例：指定程序在特定工作区或浮动/圆角设置
# windowrule = float,class:^(kitty)$,title:^(kitty)$
windowrulev2 = float, class:^(imv)$
windowrulev2 = pin,   class:^(imv)$
windowrulev2 = move 60 60, class:^(imv)$
windowrulev2 = size 640 360, class:^(imv)$

# 忽略所有程序的最大化请求
windowrule = suppressevent maximize, class:.*

# 修复 XWayland 拖拽问题
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

'';  
  };
}

